HackIllinois/api

README.md, api.js, api/config.js, api/database.js, api/index.js, api/v1/controllers/userController.js, api/v1/endpoints.js, api/v1/models/User.js, api/v1/requests/AccreditedUserCreationRequest.js, api/v1/requests/HackerUserCreationRequest.js, api/v1/requests/index.js, api/v1/services/PermissionService.js, api/v1/services/index.js, api/v1/utils/crypto.js, api/v1/utils/roles.js
This pull request covers the requirements mentioned in issue #3. The major functionality added is the ability of organizers to create "accredited" users, or users that have special responsibilities or attributes. Typically, this will just be admins creating other admins, staff, or sponsors.
Summary of application changes:
Summary of documentation changes:
=> Accredited Users

api/v1/controllers/AuthController.js, api/v1/models/MailingList.js, api/v1/models/User.js, api/v1/services/AuthService.js, api/v1/services/MailService.js, api/v1/services/PermissionService.js, api/v1/services/UserService.js
Fix for issue #24 
I've renamed all instances of `promise` and `Promise` to `_Promise`
=> standarized all instances of promise

api/v1/models/Attendee.js, api/v1/requests/AttendeeRequest.js, api/v1/services/RegistrationService.js, api/v1/utils/mail.js, api/v1/utils/registration.js, database/migration/V20170112_1719__addAttendeeTalks.sql, database/revert/V20170112_1719__addAttendeeTalks.revert.sql, test/registration.js
This pull request gives attendees the ability to tell us if they are interested in giving a short talk during the event. 
Summary of application changes:
Summary of database changes:
=> Attendee (Lightning) Talks

api/v1/models/Attendee.js, api/v1/requests/AttendeeRequest.js, api/v1/services/RegistrationService.js
I accidentally removed the `projects` key from some places where it was needed. It's back now.
=> Fix Attendee Projects

api/v1/utils/database.js
A reference error made it through the last merge. This fixes that issue.
=> Hotfix Version 0.0.2

api/v1/controllers/PermissionController.js, api/v1/controllers/StatsController.js, api/v1/controllers/index.js, api/v1/index.js, api/v1/services/PermissionService.js, api/v1/services/StatsService.js, api/v1/services/index.js
Added Attendee Stats feature for organizers.
Summary of application changes:
=> Attendee Statistics

api/v1/controllers/EcosystemController.js, api/v1/controllers/UserController.js, api/v1/services/UserService.js, test/user.js
Adds admin endpoint to delete non attendee users by email and updates User wiki.
Application changes:
=> Delete User (For Admins)

api/v1/controllers/EcosystemController.js, api/v1/controllers/UserController.js, api/v1/services/UserService.js, test/user.js
Reverts HackIllinois/api-2017#65. I do not think that it's a good idea to have a feature like this unless it is possible to delete a user in-full. Otherwise this feels half-baked.
=> Revert User Deletion

api/v1/services/RegistrationService.js
Need to format the category names for the filter route
=> Applicant util hotfix

api/v1/controllers/MailController.js
Use lodash to see if listname is an accepted list
=> Mail Route Fix

api/v1/controllers/RegistrationController.js
=> Attendee Information for Hosts Tweak

api/v1/controllers/CheckInController.js, api/v1/controllers/UserController.js
This pull request allows all hosts to retrieve basic user information.
=> User Retrieval Fix

api/v1/controllers/StatsController.js, api/v1/services/StatsService.js
=> Fix for RSVP'ed stats

api/v1/middleware/response.js
=> Bugfix for post response middleware

api/logging.js, api/v1/index.js, api/v1/middleware/auth.js, api/v1/services/AuthService.js, api/v1/utils/logs.js
1. Request is received, and assigned an id, then logged
1. Request is resolved after passing through various controller middleware, then logged
1. Request either succeeds and the response is logged, or it fails and the error is logged
=> Enhanced logging process

Vagrantfile
=> VagrantFix

.travis.yml, package.json
=> Updated .travis.yml

.travis.yml
The configuration path in `.travis.yml` is incorrect. This PR should fix that.
=> Fix Deployment Configuration Path

.travis.yml, scripts/install/deps.sh, scripts/install/flyway.sh
=> Removed sudo from deployment scripts

scripts/install/deps.sh, scripts/install/flyway.sh
=> Modified deploy scripts

.travis.yml, scripts/install/flyway.sh
=> Attempt to resolve flyway path on travis

.travis.yml, scripts/install/flyway.sh
=> Modified deployment script

.travis.yml
=> Deploy prod config with continuous delivery

.gitignore, .travis.yml
=> Stage prod config for deploy in Travis

.gitignore, .travis.yml
=> Revert "Stage prod config for deploy in Travis"

README.md, api/config.js, docs/Announcements.md, docs/Applicant-Decision-Utils.md, docs/Attendee-Statistics-Documentation.md, docs/Auth-Documentation.md, docs/Check-In-Documentation.md, docs/Ecosystems-Documentation.md, docs/Errors-Documentation.md, docs/Events-Documentation.md, docs/Health-Check-Documentation.md, docs/Home.md, docs/Permission-Documentation.md, docs/Project-Documentation.md, docs/RSVP-Documentation.md, docs/Registration-Documentation-(Attendee).md, docs/Registration-Documentation-(Mentor).md, docs/Universal-Tracking-Documenation.md, docs/Upload-Documentation.md, docs/User-Documentation.md
=> Update Application Port

api/v1/controllers/UserController.js
-[x] Update reference to mailing templates
=> Password reset bugfix

api/v1/middleware/request.js, api/v1/requests/AttendeeRequest.js, api/v1/requests/Request.js, docs/Registration-Documentation-(Attendee).md
=> Request Bugfixes

api/v1/services/RegistrationService.js
=> Bugfix Activate Attendee Role

api/v1/controllers/RegistrationController.js, api/v1/services/MailService.js, config/development.json.template, config/production.json.template, config/test.json.template
=> Registration Confirmation

config/production.json.template
=> Adjusted prod config template

api/v1/controllers/RegistrationController.js
=> Fixed Substitution Bug

api/v1/controllers/UserController.js
=> Serve UserRoles when fetching user

api/v1/controllers/RegistrationController.js, api/v1/utils/storage.js, config/development.json.template, config/production.json.template
=> Various Bugfixes

api/v1/models/AttendeeLongForm.js, api/v1/requests/AttendeeRequest.js, database/migration/V20161226_0927__createAttendees.sql, docs/Registration-Documentation-(Attendee).md
=> Updated size of long form

api/v1/controllers/RegistrationController.js, api/v1/controllers/UserController.js
=> Fix: Blocking Email Calls 

api/v1/controllers/RSVPController.js, api/v1/controllers/RegistrationController.js, api/v1/services/RegistrationService.js
=> RSVP Fixes

api/v1/controllers/EventController.js
=> Change permission on location/all

api/v1/controllers/EventController.js
=> Revert "Change permission on location/all"

database/migration/V20180207_1335__changeRSVPUnique.sql
=> Bugfix rsvp update

api/v1/controllers/UploadController.js
=> Allow non activated attendees to upload resumes

api/v1/controllers/EventController.js, api/v1/controllers/RSVPController.js
=> Allow non active attendees to get their rsvp

api/v1/controllers/MailController.js
=> Fix bug in mail list controller

api/v1/controllers/RSVPController.js, config/development.json.template, config/production.json.template, config/test.json.template
=> Rsvp email confirmations and updates

api/v1/services/StatsService.js
=> Remove RSVP types from stats

api/database.js, api/v1/services/EventService.js, api/v1/utils/time.js, docs/Events-Documentation.md
=> Allow Event Creation to Specify Timezone

api/v1/services/StatsService.js, docs/Events-Documentation.md
=> Fix RSVP Stats Query from Database

api/v1/services/RSVPService.js
=> Cleanup RSVP Service

api/v1/controllers/EventController.js, api/v1/models/EventFavorite.js, api/v1/requests/EventFavoriteRequest.js, api/v1/services/EventService.js, database/migration/V20180218_2014__addEventFavorites.sql, database/revert/V20180218_2014__addEventFavorites.revert.sql, docs/Events-Documentation.md
=> Added event favorites

api/v1/controllers/RSVPController.js, api/v1/controllers/RecruiterInterestController.js, api/v1/services/RSVPService.js
=> Fix RSVP Get

api/v1/controllers/RegistrationController.js
=> Return attendee id in fetchAttendeeForHost

api/config.js, api/v1/controllers/CheckInController.js, config/development.json.template, config/production.json.template
=> CheckIn Slack Invites

api/config.js, api/v1/controllers/CheckInController.js, api/v1/controllers/RegistrationController.js, config/development.json.template, config/production.json.template
=> Slack Checkin

api/config.js, api/v1/controllers/CheckInController.js, config/development.json.template, config/production.json.template
=> Revert "Slack Checkin"

api/config.js, api/v1/controllers/CheckInController.js, config/development.json.template, config/production.json.template
=> Revert "CheckIn Slack Invites"
